---
- name: Install docker and docker-compose
  hosts: sosman
    # become: true
    # - name: Install Docker
      # gather_facts: No
      # hosts: mansos
    
  tasks:
        - name: Install yum utils
          yum:
            name: yum-utils
            state: latest
    
        - name: Install device-mapper-persistent-data
          yum:
            name: device-mapper-persistent-data
            state: latest
    
        - name: Install lvm2
          yum:
            name: lvm2
            state: latest
    
        - name: Add Docker repo
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo
          become: yes
    
        # - name: Install Docker
        #   package:
        #     name: docker-ce
        #     state: present
        #   become: yes
    
        # - name: Start Docker service
        #   service:
        #     name: docker
        #     state: started
        #     enabled: yes
        #   become: yes

        # - name: Install docker-compose
        #   get_url: 
        #     url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        #     dest: /usr/local/bin/docker-compose
        #     mode: 'u+x,g+x'
        
        - name: Install git
          yum:
            name: git
            state: latest
        
        - name: Create Directory /services/data
          file:
            path: /services/data
            state: directory
            mode: '0755'
          
        - name: Clone a repo with separate git directory
          git:
            repo: https://github.com/johannesanchez/public-apps.git
            dest: /services
            separate_git_dir: /services/public-apps.git


